services:
  - type: web
    name: program-inventory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app --timeout 120
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true